cart/urls.py
from django.urls import path
from .views import cart_summary, cart_add, cart_update, cart_delete

app_name = 'cart'

urlpatterns = [
    path('', cart_summary, name='cart_summary'),
    path('cart-add/', cart_add, name='cart_add'),
    path('cart-update/', cart_update, name='cart_update'),
    path('cart-delete/', cart_delete, name='cart_delete')
]

ecmprj/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('core', include('core.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import home, about, login_user, logout_user, user_register, product, category, categories_summary, \
    user_update, password_update, info_update, search_items

app_name = 'store'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('user-register/', user_register, name='user_register'),
    path('user-update/', user_update, name='user_update'),
    path('info-update/', info_update, name='info_update'),
    path('password-update/', password_update, name='password_update'),
    path('product/<int:pk>/', product, name='product'),
    path('category/<slug:slug>/', category, name='category'),
    path('categories_summary/', categories_summary, name='categories_summary'),
    path('search/', search_items, name='search')

]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render, get_object_or_404
from .cart import Cart
from store.models import Product
from django.http import JsonResponse
from django.contrib import messages


def cart_summary(request):
    # get the cart
    cart = Cart(request)
    cart_products = cart.get_prods()
    quantities = cart.get_quants()
    totals = cart.get_total()
    context = {
        'cart_products': cart_products,
        'quantities': quantities,
        'totals': totals
    }
    return render(request, 'cart/cart_summary.html', context)

def cart_add(request):
    #get the cart
    cart = Cart(request)
    # test for POST
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('quantity'))
        product = get_object_or_404(Product, id=product_id)

        cart.add(product=product, quantity=product_qty)

        cart_quantity = cart.__len__()

        response = JsonResponse({'qty': cart_quantity})
        messages.success(request, ('Items added to your cart...'))
        return response


def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        cart.delete(product=product_id)
        response = JsonResponse({'product': product_id})
        messages.success(request, ('Items deleted from your cart...'))

        return response


def cart_update(request):
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('quantity'))

        cart.update(product=product_id, quantity=product_qty)

        response = JsonResponse({'qty': product_qty})
        messages.success(request, ('Your cart updated...'))
        return response

templates/cart/cart_summary.html
{% extends 'base.html' %}

{% block content %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Cart Summary</h1>
            <p class="lead fw-normal text-white-50 mb-0">Here you can get some information</p>
        </div>
    </div>
</header>

{% if cart_products %}
    {% for product in cart_products %}
    <br>

    <div class="card w-75 d-flex flex-row align-items-start">
      <img src="{{ product.image.url }}" alt="Image" class="img-fluid" style="width: 267px;  max-height: 180px; object-fit: cover;">
      <div class="card-body">
        <h5 class="card-title">{{ product.name }}</h5>
          {% if product.is_sale %}
        <span class="text-muted text-decoration-line-through">${{ product.price }}</span>

        ${{ product.discount_price }}

    {% else %}

          <h4>$ {{ product.price }}</h4>

    {% endif %}

        <div style="display: flex; align-items: center;">
          <button style="width: 30px; height: 30px; font-size: 20px; text-align: center;" class="decrease-btn" data-id="{{ product.id }}">-</button>
          <input type="text" class="quantity-input" id="quantity-{{ product.id }}"
            {% for key, value in quantities.items %}
                {% if key == product.id|slugify %}
                    value="{{ value }}"
                {% endif %}
            {% endfor %}
            readonly
            style="width: 50px; text-align: center; margin: 0 10px;">
          <button style="width: 30px; height: 30px; font-size: 20px; text-align: center;" class="increase-btn" data-id="{{ product.id }}">+</button>
        </div>

        <p class="card-text">Description: {{ product.description }}</p>
          <button class="btn btn-danger delete-product" type="button" data-index="{{ product.id }}"><i class="fa fa-solid fa-trash"></i> Remove item</button>
        <a href="#" class="btn btn-primary">Button</a>
      </div>
    </div>
    {% endfor %}
</br>
</br>
<h3>Total: $ {{ totals }}</h3>
{% else %}
    <br><br>
    <h1>There is no product yet. <a href="{% url 'store:home' %}">Go shopping</a></h1>
{% endif %}
<br><br><br><br>

<script>
    // UPDATE
    function updateCart(productId, quantity) {
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_update" %}',  // Django URL to update the cart
            data: {
                product_id: productId,
                quantity: quantity,
                csrfmiddlewaretoken: '{{ csrf_token }}',  // CSRF token for Django
                action: 'post'
            },
            success: function(response) {
                location.reload();
                console.log("Cart updated successfully");
                // Optional: Add logic here if you want to display a message or update other UI elements
            },
            error: function(xhr, errmsg, err) {
                console.log("Error updating cart: ", errmsg);
            }
        });
    }

    // Event delegation for increase button
    document.addEventListener('click', function(e) {
        if (e.target.classList.contains('increase-btn')) {
            const productId = e.target.getAttribute('data-id');
            let quantityInput = document.getElementById('quantity-' + productId);
            let currentValue = parseInt(quantityInput.value);
            quantityInput.value = currentValue + 1;

            // Call the function to update the cart with the new quantity
            updateCart(productId, quantityInput.value);
        }

        // Event delegation for decrease button
        if (e.target.classList.contains('decrease-btn')) {
            const productId = e.target.getAttribute('data-id');
            let quantityInput = document.getElementById('quantity-' + productId);
            let currentValue = parseInt(quantityInput.value);
            if (currentValue > 1) {
                quantityInput.value = currentValue - 1;

                // Call the function to update the cart with the new quantity
                updateCart(productId, quantityInput.value);
            }
        }
    });

       // DELETE
    $(document).on('click', '.delete-product', function(e) {
    e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_delete" %}',  // Django URL to update the cart
            data: {
                product_id: $(this).data('index'),
                csrfmiddlewaretoken: '{{ csrf_token }}',  // CSRF token for Django
                action: 'post'
            },
            success: function(response) {
                console.log("Item deleted successfully");
                location.reload();
            },
            error: function(xhr, errmsg, err) {
                console.log("Error deleting cart: ", errmsg);
            }
        });
    }
    )
</script>

{% endblock content %}