cart/urls.py
from django.urls import path
from .views import cart_summary, cart_add, cart_update, cart_delete

app_name = 'cart'

urlpatterns = [
    path('', cart_summary, name='cart_summary'),
    path('cart-add/', cart_add, name='cart_add'),
    path('cart-update/', cart_update, name='cart_update'),
    path('cart-delete/', cart_delete, name='cart_delete')
]

ecmprj/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('core', include('core.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import home, about, login_user, logout_user, user_register, product, category, categories_summary, \
    user_update, password_update, info_update, search_items

app_name = 'store'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('user-register/', user_register, name='user_register'),
    path('user-update/', user_update, name='user_update'),
    path('info-update/', info_update, name='info_update'),
    path('password-update/', password_update, name='password_update'),
    path('product/<int:pk>/', product, name='product'),
    path('category/<slug:slug>/', category, name='category'),
    path('categories_summary/', categories_summary, name='categories_summary'),
    path('search/', search_items, name='search')

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Shop Homepage - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    </head>
    <body>
    {% block navigation %}
        {% include 'navigation.html' %}
    {% endblock %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}


    {% endblock content %}
    <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/navigation.html
<!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'store:home' %}"><b>BookStore</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'store:home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'store:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'store:user_update' %}">User update</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'store:logout' %}">Logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'store:login' %}">Login</a></li>
                        {% endif %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'store:categories_summary' %}">All categories</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                {% for category in categories %}
                                    <li><a class="dropdown-item" href="{% url 'store:category' category.slug %}">{{ category.name }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" action="{% url 'store:search' %}" method="post">
                        {% csrf_token %}
                      <input class="form-control mr-sm-2" type="search" name="searched" placeholder="Search" aria-label="Search">
                      <button class="btn btn-outline-success my-2 my-sm-2" style="margin-right: 10px; margin-left: 5px" type="submit">Search</button>
                    </form>
                    <form class="d-flex">
                            <a class="btn btn-outline-dark" href="{% url 'cart:cart_summary' %}" role="button"><i class="bi-cart-fill me-1"></i>
                            Cart
                            <span class="badge bg-dark text-white ms-1 rounded-pill" id="cart_quantity">{{ cart|length }}</span>
                            </a>
                    </form>
                </div>
            </div>
        </nav>