cart/urls.py
from django.urls import path
from .views import cart_summary, cart_add, cart_update, cart_delete

app_name = 'cart'

urlpatterns = [
    path('', cart_summary, name='cart_summary'),
    path('cart-add/', cart_add, name='cart_add'),
    path('cart-update/', cart_update, name='cart_update'),
    path('cart-delete/', cart_delete, name='cart_delete')
]

ecmprj/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('core', include('core.urls')),
    path('cart/', include('cart.urls')),
    path('payment/', include('payment.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import home, about, login_user, logout_user, user_register, product, category, categories_summary, \
    user_update, password_update, info_update, search_items

app_name = 'store'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('user-register/', user_register, name='user_register'),
    path('user-update/', user_update, name='user_update'),
    path('info-update/', info_update, name='info_update'),
    path('password-update/', password_update, name='password_update'),
    path('product/<int:pk>/', product, name='product'),
    path('category/<slug:slug>/', category, name='category'),
    path('categories_summary/', categories_summary, name='categories_summary'),
    path('search/', search_items, name='search')

]

store/models.py
import datetime
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_modified = models.DateTimeField(User, auto_now=True)
    phone = models.CharField(max_length=20, blank=True)
    adress1 = models.CharField(max_length=200, blank=True)
    adress2 = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=200, blank=True)
    state = models.CharField(max_length=200, blank=True)
    zipcode = models.CharField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    cart = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.user.username

    #create a profile when user signs up by djangos auth system
    def create_profile(sender, instance, created, **kwargs):
        if created:
            user_profile = Profile(user=instance)
            user_profile.save()

    #automating creating profile
    post_save.connect(create_profile, sender=User)


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=14)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(default=0, decimal_places=2, max_digits=8)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1, related_name='products')
    description = models.CharField(max_length=250, default='', blank=True, null=True)
    image = models.ImageField(upload_to='uploads/product/')
    is_sale = models.BooleanField(default=False)
    discount = models.DecimalField(default=0, decimal_places=1, max_digits=3)

    def __str__(self):
        return self.name

    @property
    def discount_price(self):
        if self.is_sale and self.discount > 0:
            discount_amount = self.price * (self.discount / 100)
            return round(self.price - discount_amount, 2)
        return self.price


class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    address = models.CharField(max_length=100, default='', blank=True)
    phone = models.CharField(max_length=14, default='', blank=True)
    date = models.DateField(default=datetime.datetime.today)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.product

store/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm
from django import forms

from store.models import Profile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
    first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
    last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'


class UserUpdateForm(UserChangeForm):
    # hiding password warning message
    password = None

    email = forms.EmailField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
    first_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
    last_name = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'


class PasswordUpdateForm(SetPasswordForm):
    class Meta:
        model = User
        fields = ['new_password1', 'new_password2']

    def __init__(self, *args, **kwargs):
        super(PasswordUpdateForm, self).__init__(*args, **kwargs)

        self.fields['new_password1'].widget.attrs['class'] = 'form-control'
        self.fields['new_password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['new_password1'].label = ''
        self.fields['new_password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

        self.fields['new_password2'].widget.attrs['class'] = 'form-control'
        self.fields['new_password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['new_password2'].label = ''
        self.fields['new_password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'


class UserInfoForm(forms.ModelForm):
    phone = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your phone number...'}), required=False)
    adress1 = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your adress...'}), required=False)
    adress2 = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your adress...'}), required=False)
    city = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your city...'}), required=False)
    state = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your state...'}), required=False)
    zipcode = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your zipcode...'}), required=False)
    country = forms.CharField(label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Your country...'}), required=False)

    class Meta:
        model = Profile
        fields = ('phone', 'adress1', 'adress2', 'city', 'state', 'zipcode', 'country')

store/views.py
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect
from cart.cart import Cart
from payment.forms import ShippingForm
from .models import Product, Category, Profile
from .forms import SignUpForm, UserUpdateForm, PasswordUpdateForm, UserInfoForm
import json


def home(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    context = {
        'products': products,
        'categories': categories
    }
    return render(request, 'store/index.html', context)


def product(request, pk):
    product = Product.objects.get(id=pk)
    context = {
        'product': product
    }
    return render(request, 'store/product.html', context)


def category(request, slug):
    try:
        ctgry = Category.objects.get(slug=slug)
        products = Product.objects.filter(category=ctgry)
        context = {
         'category': ctgry,
         'products': products
        }
        return render(request, 'store/category.html', context)
    except:
        messages.success(request, ("That category doesn't exists."))
        return redirect('store:home')


def categories_summary(request):
    categories = Category.objects.all()
    context = {
        'categories': categories
    }

    return render(request, 'store/categories_summary.html', context)


def search_items(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        if searched:
            result = Product.objects.filter(Q(name__icontains=searched) | Q(description__icontains=searched))
            context = {
                'searched': searched,
                'result': result
            }
            return render(request, 'store/search.html', context)
    return render(request, 'store/search.html')


def about(request):
    return render(request, 'store/about.html')


def login_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

            # cart stuff
            current_user = Profile.objects.get(user__id=request.user.id)
            saved_cart = current_user.cart
            if saved_cart:
                # convert to dict using json
                converted_cart = json.loads(saved_cart)
                # add the loaded cart dictionary to session
                cart = Cart(request)
            #     loop through dict and add items to the cart

                for key, value in converted_cart.items():
                    cart.db_add(product=key, quantity=value)


            messages.success(request, ("You have been logged in..."))
            return redirect('store:home')
        else:
            messages.success(request, ("There was an error. Please try again..."))
            return redirect('store:login')
    return render(request, 'store/login.html')


def logout_user(request):
    logout(request)
    messages.success(request, ("You have been logged out..."))
    return redirect('store:home')


def user_register(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ("You registered successfully!"))
            return redirect('store:home')
        else:
            messages.success(request, ("Oops! There was a problem in the form... Please try again..."))
            return redirect('store:user_register')
    else:
        context = {
            'form': form
        }
        return render(request, 'store/user_register.html', context)


def user_update(request):

    if request.user.is_authenticated:
        user = request.user
        form = UserUpdateForm(request.POST or None, instance=user)
        shipping_form = ShippingForm(request.POST or None, instance=user)
        if form.is_valid():
            form.save()
            login(request, user)
            return redirect('store:login')
        else:
            context = {
                'form': form
            }
            messages.warning(request, ('Some errors occured... Please check and try again...'))
            return render(request, 'store/user_update.html', context)
    else:
        messages.warning(request, ('You must logged in...'))
        return redirect('store:login')


def info_update(request):
    if request.user.is_authenticated:
        user = request.user
        profile, created = Profile.objects.get_or_create(user=user)
        form = UserInfoForm(request.POST or None, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your informations has been changed...')
            return redirect('store:home')
        return render(request, 'store/info_update.html', {'form': form})
    else:
        messages.success(request, 'You must be logged in...')
        return redirect('store:home')


def password_update(request):
    if request.user.is_authenticated:
        user = request.user

        if request.method == 'POST':
            form = PasswordUpdateForm(user, request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, ('Your password changed successfully!'))
                # login(request, user)
                return redirect('store:home')
            else:
                for error in list(form.errors.values()):
                    messages.error(request, error)
                    return redirect('store:password_update')
        else:
            form = PasswordUpdateForm(user)
            return render(request, 'store/password_update.html', {'form': form})
    else:
        messages.warning(request, ('You must be logged in...'))
        return redirect('store:login')

templates/store/categories_summary.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">All categories</h1>
            <p class="lead fw-normal text-white-50 mb-0">Choose your category...</p>
        </div>
    </div>
</header>
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for category in categories %}
            <div class="col mb-5">
                <div class="card h-100">
                    <div id="carouselExampleInterval{{ category.id }}" class="carousel slide" data-bs-ride="carousel">
                      <div class="carousel-inner">
                      {% for product in category.products.all %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %}" data-bs-interval="3000">
                            <img src="{{ product.image.url }}" style="max-width: 267px; max-height: 180px; object-fit: cover;" class="d-block w-100" alt="{{ product.name }}">
                        </div>
                      {% endfor %}
                      </div>
                    </div>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <h5 class="fw-bolder">{{ category.name }}</h5>

                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'store:category' category.slug %}">View products</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

    {% endblock content %}

templates/store/category.html
{% extends 'base.html' %}

{% block content %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">{{ category.name }}</h1>
            <p class="lead fw-normal text-white-50 mb-0">...</p>
        </div>
    </div>
</header>

</br>
</br>
</br>
</br>

<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in products %}
            <div class="col mb-5">
                <div class="card h-100">
                    {% if product.is_sale %}
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem"> {{ product.discount }}% Sale</div>
                    {% endif %}
                    <!-- Product image-->
                    <img class="card-img-top" src="{{ product.image.url }}" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ product.name }}</h5>
                            <!-- Product price-->
                            {% if product.is_sale %}
                            <span class="text-muted text-decoration-line-through">${{ product.price }}</span>

                            ${{ product.discount_price }}

                            {% else %}

                            ${{ product.price }}

                            {% endif %}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'store:product' product.id %}">View product</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
</br>
</br>
</br>

{% endblock content %}

templates/store/index.html
{% extends 'base.html' %}
{% block content %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Shop in style</h1>
            <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
        </div>
    </div>
</header>
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in products %}
            <div class="col mb-5">
                <div class="card h-100">
                    {% if product.is_sale %}
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem"> {{ product.discount }}% Sale</div>
                    {% endif %}
                    <!-- Product image-->
                    <img class="card-img-top" style="max-width: 267px; max-height: 180px; object-fit: cover;" src="{{ product.image.url }}" alt="..." />
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ product.name }}</h5>
                            <!-- Product price-->
                            {% if product.is_sale %}
                            <span class="text-muted text-decoration-line-through">${{ product.price }}</span>

                            ${{ product.discount_price }}

                            {% else %}

                            ${{ product.price }}

                            {% endif %}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'store:product' product.id %}">View product</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

    {% endblock content %}

templates/store/info_update.html
{% extends 'base.html' %}
{% block content %}

    {% block navigation %}
    {% endblock %}

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Update additional informations</h1>
            <p class="lead fw-normal text-white-50 mb-0">Here you can change your shopping informations...</p>
        </div>
    </div>
</header>

</br>
</br>
</br>
<strong>Billing information</strong>
</br>
</br>

<div class="d-flex justify-content-center">
  <form method="post" action="{% url 'store:info_update' %}"> {% csrf_token %}

      {{ form.as_p }}
        </br>
        </br>

      {{ shipping_form.as_p }}
        </br>
        </br>

  <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-success btn-block mb-4">Save changes</button>

</form>
</br>
</br>
</div>


</br>
</br>
</br>
</br>

{% endblock content %}

templates/store/login.html
{% extends 'base.html' %}
{% block content %}

    {% block navigation %}
    {% endblock %}

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">Login</h1>
            <p class="lead fw-normal text-white-50 mb-0">Welcome back. We missed you</p>
        </div>
    </div>
</header>

</br>
</br>
</br>
</br>

<div class="d-flex justify-content-center">
  <form method="post" action="{% url 'store:login' %}"> {% csrf_token %}
  <!-- Email input -->
  <div data-mdb-input-init class="form-outline mb-4">
    <input type="text" class="form-control" name="username" placeholder="Enter your username..."/>

  </div>

  <!-- Password input -->
  <div data-mdb-input-init class="form-outline mb-4">
    <input type="password" class="form-control" name="password" placeholder="Enter your password..."/>
  </div>

  <!-- 2 column grid layout for inline styling -->
  <div class="row mb-4">

    <div class="col">
      <!-- Simple link -->
      <a href="#!">Forgot password?</a>
    </div>
  </div>

  <!-- Submit button -->
  <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Login</button>

  <!-- Register buttons -->
  <div class="text-center">
    <p>Not a member? <a href="{% url 'store:user_register' %}">Register</a></p>
  </div>
</form>
</div>

</br>
</br>
</br>
</br>

{% endblock content %}

templates/store/logout.html
{% extends 'base.html' %}

{% block content %}


{% endblock content %}

templates/store/password_update.html
{% extends 'base.html' %}
{% block content %}

    {% block navigation %}
    {% endblock %}

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">User password update</h1>
            <p class="lead fw-normal text-white-50 mb-0">Here you can change your password...</p>
        </div>
    </div>
</header>

</br>
</br>
</br>
</br>

<div class="d-flex justify-content-center">
  <form method="post" action="{% url 'store:password_update' %}"> {% csrf_token %}

      {{ form.as_p }}
        </br>
        </br>

  <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Change password</button>

</form>
</div>

</br>
</br>
</br>
</br>

{% endblock content %}

templates/store/product.html
{% extends 'base.html' %}


{% block content %}


</br>
</br>
</br>
</br>

<div class="card w-75 d-flex flex-row align-items-start">
  <img src="{{ product.image.url }}" alt="Image" class="img-fluid" style="width: 300px;  max-height: 250px; object-fit: cover;">
  <div class="card-body">
    <h5 class="card-title">{{ product.name }}</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
      {% if product.is_sale %}
        <span class="text-muted text-decoration-line-through">${{ product.price }}</span>

        ${{ product.discount_price }}

    {% else %}

        ${{ product.price }}

    {% endif %}
    <div style="display: flex; align-items: center;">
      <button style="width: 30px; height: 30px; font-size: 20px; text-align: center;" id="decrease">-</button>
      <input type="text" id="quantity" value="1" readonly
             style="width: 50px; text-align: center; margin: 0 10px;">
      <button style="width: 30px; height: 30px; font-size: 20px; text-align: center;" id="increase">+</button>
    </div>


    <div class="text-center">
        <a class="btn btn-outline-success mt-auto" href="#"><i class="fa-solid fa-heart"></i> Add to saved</a>
        <button type="button" value="{{ product.id }}" class="btn btn-secondary" id="add-cart">Add to cart</button>
    </div>
  </div>
</div>







</br>
</br>
</br>
</br>

<script>
    // Check if "Add to Cart" button is pressed
    $(document).on('click', '#add-cart', function(e){
        e.preventDefault();

        // Get the selected quantity from the input field
        let quantity = parseInt(document.getElementById('quantity').value);

        // Send an AJAX POST request
        $.ajax({
            type: 'POST',
            url: '{% url 'cart:cart_add' %}',
            data: {
                product_id: $('#add-cart').val(),
                quantity: quantity,  // Include the selected quantity
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },

            success: function(json){
                document.getElementById("cart_quantity").textContent = json.qty;
                location.reload();
            },

            error: function(xhr, errmsg, err){
                // Handle error
            }
        });
    });

    // Increase quantity
    document.getElementById('increase').addEventListener('click', function() {
        let quantityInput = document.getElementById('quantity');
        let currentValue = parseInt(quantityInput.value);
        quantityInput.value = currentValue + 1;
    });

    // Decrease quantity
    document.getElementById('decrease').addEventListener('click', function() {
        let quantityInput = document.getElementById('quantity');
        let currentValue = parseInt(quantityInput.value);
        if (currentValue > 1) {
            quantityInput.value = currentValue - 1;
        }
    });
</script>
{% endblock %}

templates/store/user_register.html
{% extends 'base.html' %}
{% block content %}

    {% block navigation %}
    {% endblock %}

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">User register</h1>
            <p class="lead fw-normal text-white-50 mb-0">Welcome...</p>
        </div>
    </div>
</header>

</br>
</br>
</br>
</br>

<div class="d-flex justify-content-center">
  <form method="post" action="{% url 'store:user_register' %}"> {% csrf_token %}

      {{ form.as_p }}
        </br>
        </br>

  <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Register</button>

</form>
</div>

</br>
</br>
</br>
</br>

{% endblock content %}

templates/store/user_update.html
{% extends 'base.html' %}
{% block content %}

    {% block navigation %}
    {% endblock %}

<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">User update</h1>
            <p class="lead fw-normal text-white-50 mb-0">Here you can change your profile informations...</p>
        </div>
    </div>
</header>

</br>
</br>
</br>
</br>

<div class="d-flex justify-content-center">
  <form method="post" action="{% url 'store:user_update' %}"> {% csrf_token %}

      {{ form.as_p }}
        </br>
        </br>

  <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-success btn-block mb-4">Update profile</button>

</form>
</br>
</br>
</div>
<div class="d-flex justify-content-center">
    <a href="{% url 'store:info_update' %}" class="btn btn-primary btn-block mb-4">Change shopping info</a>
</div>
<div class="d-flex justify-content-center">
    <a href="{% url 'store:password_update' %}" class="btn btn-primary btn-block mb-4">Change password</a>
</div>

</br>
</br>
</br>
</br>

{% endblock content %}